openapi: '3.0.3'

info:
  title: Video Upload & Transcription API
  version: 1.0.0
  description: API for uploading videos, transcribing them using OpenAI Whisper, and retrieving stored transcripts.

servers:
  - url: http://localhost:3010/api/v0

paths:
  /upload:
    post:
      summary: Upload a video for transcription
      description: Uploads a video file, processes it with OpenAI Whisper, and stores the transcript.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: The video file to be uploaded.
      responses:
        200:
          description: Video uploaded successfully and transcribed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  videoId:
                    type: integer
                  transcript:
                    type: string
        400:
          description: No video file provided or invalid request.
        500:
          description: Internal server error (processing failed).
        default:
          description: Unexpected error.
  /lesson:
    post:
      summary: Add a new lesson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                videoId:
                  type: string
                lessonPlan:
                  type: string
                quiz:
                  type: string
                notes:
                  type: string
      responses:
        201:
          description: Lesson added successfully
        500:
          description: Internal server error
    get:
      summary: Get all lessons
      responses:
        200:
          description: List of lessons
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    videoId:
                      type: string
                    data:
                      type: object
                      properties:
                        name:
                          type: string
                        lessonPlan:
                          type: string
                        quiz:
                          type: string
                        notes:
                          type: string
        500:
          description: Internal server error
  /lesson/{id}:
   get:
      summary: Get a specific lesson by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Returns the lesson data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  videoId:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      lessonPlan:
                        type: string
                      quiz:
                        type: string
                      notes:
                        type: string
        404:
          description: Lesson not found
        500:
          description: Internal server error
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string